functional_em_edits
UCD-SERG/serocalculator pull request #118
Opened 2024-04-02 09:23 UTC by chrisorwa

This has the function aliases and em-edits.

2024-04-02 09:44 UTC, chrisorwa commented
Hi @d-morrison , there was some confusion with your changes (em-edits). I have closed the other PR (create function aliases).

2024-04-23 06:23 UTC, d-morrison requested changes
See comments below and in https://github.com/UCD-SERG/serocalculator/issues/111.

2024-04-23 06:23 UTC, d-morrison commented on NAMESPACE
> +export(df_to_array)
`df_to_array()` shouldn't be exported

2024-04-23 06:23 UTC, d-morrison commented on R/df_to_array.R
it looks like you renamed `df.to.array.R` to `df_to-array.R`, but then somehow `df.to.array.R` is still present. Please delete the `df.to.array.R` file and keep the `df_to_array.R` file.

2024-04-23 06:23 UTC, d-morrison commented on R/df_to_array.R
> +#'   df %>% serocalculator:::df.to.array(dim_var_names = c("parameter", "Species"))
This example is already provided for `df_to_array()` below; no need to duplicate it for each alias (please delete this version). Otherwise, the examples are doubled in the documentation page (see `?df_to_array` in this branch):

<img width="658" alt="image" src="https://github.com/UCD-SERG/serocalculator/assets/2474437/fa892e01-4ac7-4e80-8121-6594964fa011">

2024-04-23 11:18 UTC, chrisorwa commented on NAMESPACE
> +export(df_to_array)
I have removed the `@export` keyword.

2024-04-23 11:19 UTC, chrisorwa commented on R/df_to_array.R
This is done.

2024-05-08 19:32 UTC, d-morrison requested changes
Good work on this PR! I'm requesting a few more changes (see comments); then it should be good to go.

2024-05-08 19:32 UTC, d-morrison commented on R/sim.cs-utils.r
> +row_longitudinal_parameter <- ldpar
- [ ] do the `lifecycle` process for this function
- [ ] don't export this function

2024-05-08 19:32 UTC, d-morrison commented on R/sim.cs-utils.r
> +mk_baseline <- mkbaseline
- [ ] do the `lifecycle` process for this function
- [ ] don't export this function

2024-05-08 19:32 UTC, d-morrison commented on vignettes/articles/scrubTyphus_example.Rmd
> +  filter(!is.na(value)) %>% #
accidental comment stub?

2024-05-09 06:12 UTC, chrisorwa commented on vignettes/articles/scrubTyphus_example.Rmd
> +  filter(!is.na(value)) %>% #
Yes it is.

2024-05-09 18:07 UTC, d-morrison approved these changes
Looks great - thanks!

2024-05-09 18:07 UTC, merged