Load Curve Data from Environment (as_curve_data)
UCD-SERG/serocalculator pull request #145
Opened 2024-06-30 20:02 UTC by chrisorwa

The function `as_curve_data` that converts objects to curve data

2024-07-02 15:42 UTC, d-morrison requested changes
see comments

2024-07-02 15:42 UTC, d-morrison commented on R/as_curve_data.R
as far as I can tell, only this file's edits need to be in this PR; please resubmit a minimal PR

2024-07-02 15:42 UTC, d-morrison commented on R/as_curve_data.R
> +  if(all(is.element(c('y0','y1', 'alpha'), curve_data %>% names()))){
why are we only checking for three of the five parameters?

2024-07-02 15:42 UTC, d-morrison commented on R/as_curve_data.R
> +  }
instead of *copy*ing this code out of `load_curve_params()`, please *cut* it out and replace what was cut with a call to this function.

2024-07-03 12:29 UTC, chrisorwa commented
Closing the PR to correct the branching.

2024-07-03 12:29 UTC, closed without merging