add as_curve_data
UCD-SERG/serocalculator pull request #170
Opened 2024-07-09 09:15 UTC by chrisorwa

2024-07-09 14:21 UTC, d-morrison requested changes
Thanks! See comments below.

2024-07-09 14:21 UTC, d-morrison commented on R/as_curve_data.R
> +curve_converter <- function(data, antigen_isos = NULL) {
decomposing out `curve_converter()` seems like unnecessary complexity; there's only two commands left in `as_curve_data()`. is there a reason for doing it this way?

2024-07-09 14:21 UTC, d-morrison commented on R/as_curve_data.R
> +    tibble::as_tibble()
none of this code is currently tested; easiest fix will be to call it in `load_curve_params()`, then tests of that function will implicitly test this function as well.

2024-07-09 14:21 UTC, d-morrison commented on R/as_curve_data.R
> +as_curve_data <- function(data, antigen_isos = NULL) {
should be called `as_curve_params()`

2024-07-16 15:54 UTC, closed without merging

2024-07-16 15:54 UTC, lokune commented
Closing it!