Update EF Vignette
UCD-SERG/serocalculator pull request #290
Opened 2024-09-27 04:43 UTC by kristinawlai

Quick fix and update of enteric fever vignette ahead of IMD presentation. 
- remove deprecated function `check_pop_data`
- Removed duplicate antibody plot
- Upgrade `est.incidence.by` to country + age 
- Update `est.incidence.by` plot 
- Reformat all code chunks to match style guide

2024-09-27 15:59 UTC, kristinawlai commented
Updated the vignette to clean it up and replace plots with those from the paper. @d-morrison I don't know if these changes warrant an item in NEWS.md so the changelog is failing.

2024-09-27 18:33 UTC, d-morrison requested changes
Thanks for this PR! Please see comments.

2024-09-27 18:33 UTC, d-morrison commented on vignettes/articles/enteric_fever_example.Rmd
> +  load_curve_params()
does this step duplicate lines 69-71?

2024-09-27 18:33 UTC, d-morrison commented on vignettes/articles/enteric_fever_example.Rmd
> +  load_pop_data()
let's replace `load_pop_data()` with  `readr::read_rds() %>% as_pop_data()` which is a more typical workflow (see #148)

2024-09-27 18:35 UTC, d-morrison commented
> Updated the vignette to clean it up and replace plots with those from the paper. @d-morrison I don't know if these changes warrant an item in NEWS.md so the changelog is failing.

I think it's worth adding a line to NEWS.md; some of our users might appreciate the heads-up that we've improved the vignette.

2024-09-27 19:17 UTC, d-morrison commented
also, please clear out the warnings produced by `est.incidence.by()`:

![image](https://github.com/user-attachments/assets/2b38cc9a-1208-4aa9-bcfd-7ce1c84233b3)

(the warnings tell you how to get rid of them)

2024-09-28 18:12 UTC, kristinawlai commented
@d-morrison the OSF dataset for curve params is actually missing all of the strata so it should be used unstratified. I added noise_strata_varnames, but not sure if it helps. Also added more explanation in the text. 

> also, please clear out the warnings produced by `est.incidence.by()`:
> 
> ![image](https://private-user-images.githubusercontent.com/2474437/371652873-2b38cc9a-1208-4aa9-bcfd-7ce1c84233b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDM3MDgsIm5iZiI6MTcyNzU0MzQwOCwicGF0aCI6Ii8yNDc0NDM3LzM3MTY1Mjg3My0yYjM4Y2M5YS0xMjA4LTRhYTktYmNmZC03Y2UxYzg0MjMzYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTcxMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJlNjdmYzczMDM1MjYyZmY4Njk1MDU2ZjQ5NzY2ZTE3NjU0MGY0NzFlYTAzYjRmNzYxYWU4MDM5Mzc2NjQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S3s49HVl6m_ZjFFS7DTsi0LA5HbFzEnHYjrkfnbAzTQ)
> 
> (the warnings tell you how to get rid of them)

2024-09-28 22:17 UTC, d-morrison commented
> @d-morrison the OSF dataset for curve params is actually missing all of the strata so it should be used unstratified. I added noise_strata_varnames, but not sure if it helps. Also added more explanation in the text.
> 
> > also, please clear out the warnings produced by `est.incidence.by()`:
> > ![image](https://private-user-images.githubusercontent.com/2474437/371652873-2b38cc9a-1208-4aa9-bcfd-7ce1c84233b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDM3MDgsIm5iZiI6MTcyNzU0MzQwOCwicGF0aCI6Ii8yNDc0NDM3LzM3MTY1Mjg3My0yYjM4Y2M5YS0xMjA4LTRhYTktYmNmZC03Y2UxYzg0MjMzYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTcxMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJlNjdmYzczMDM1MjYyZmY4Njk1MDU2ZjQ5NzY2ZTE3NjU0MGY0NzFlYTAzYjRmNzYxYWU4MDM5Mzc2NjQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S3s49HVl6m_ZjFFS7DTsi0LA5HbFzEnHYjrkfnbAzTQ)
> > (the warnings tell you how to get rid of them)

Thanks for those edits! Since there are no stratifying variables in `curves`, you should be able to use `curve_strata_varnames = NULL` to remove the corresponding error.

There's still one error-left - the one about unbalanced observation counts across antigen-isotypes; we don't have an easy way to mute that one right now, so we should either explain it, or remove observations that have some isotypes missing (prior to calling `est.incidence.by()`.)

2024-09-29 02:59 UTC, kristinawlai commented
> > @d-morrison the OSF dataset for curve params is actually missing all of the strata so it should be used unstratified. I added noise_strata_varnames, but not sure if it helps. Also added more explanation in the text.
> > > also, please clear out the warnings produced by `est.incidence.by()`:
> > > ![image](https://private-user-images.githubusercontent.com/2474437/371652873-2b38cc9a-1208-4aa9-bcfd-7ce1c84233b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDM3MDgsIm5iZiI6MTcyNzU0MzQwOCwicGF0aCI6Ii8yNDc0NDM3LzM3MTY1Mjg3My0yYjM4Y2M5YS0xMjA4LTRhYTktYmNmZC03Y2UxYzg0MjMzYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTcxMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJlNjdmYzczMDM1MjYyZmY4Njk1MDU2ZjQ5NzY2ZTE3NjU0MGY0NzFlYTAzYjRmNzYxYWU4MDM5Mzc2NjQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S3s49HVl6m_ZjFFS7DTsi0LA5HbFzEnHYjrkfnbAzTQ)
> > > (the warnings tell you how to get rid of them)
> 
> @kristinawlai Thanks for those edits! Since there are no stratifying variables in `curves`, you should be able to use `curve_strata_varnames = NULL` to remove the corresponding error.
> 
> There's still one error left - the one about unbalanced observation counts across antigen-isotypes; we don't have an easy way to mute that one right now, so we should either explain it, or remove observations that have some isotypes missing (prior to calling `est.incidence.by()`.)

@d-morrison I thought I would try to inspect the count of antigen isotypes by adding the n for each strata to the `summary()` in line 113 (i.e. to `ab_summary` on lines 48-63 in `summary.pop_data.R`), but was having issues, so I scratched that and just added more explanation in lines 238-244 for now. Feel free to tinker with it if you'd like, otherwise I think it can be updated later.

2024-09-30 06:25 UTC, d-morrison commented
> > > @d-morrison the OSF dataset for curve params is actually missing all of the strata so it should be used unstratified. I added noise_strata_varnames, but not sure if it helps. Also added more explanation in the text.
> > > > also, please clear out the warnings produced by `est.incidence.by()`:
> > > > ![image](https://private-user-images.githubusercontent.com/2474437/371652873-2b38cc9a-1208-4aa9-bcfd-7ce1c84233b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDM3MDgsIm5iZiI6MTcyNzU0MzQwOCwicGF0aCI6Ii8yNDc0NDM3LzM3MTY1Mjg3My0yYjM4Y2M5YS0xMjA4LTRhYTktYmNmZC03Y2UxYzg0MjMzYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMTcxMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJlNjdmYzczMDM1MjYyZmY4Njk1MDU2ZjQ5NzY2ZTE3NjU0MGY0NzFlYTAzYjRmNzYxYWU4MDM5Mzc2NjQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S3s49HVl6m_ZjFFS7DTsi0LA5HbFzEnHYjrkfnbAzTQ)
> > > > (the warnings tell you how to get rid of them)
> > 
> > 
> > @kristinawlai Thanks for those edits! Since there are no stratifying variables in `curves`, you should be able to use `curve_strata_varnames = NULL` to remove the corresponding error.
> > There's still one error left - the one about unbalanced observation counts across antigen-isotypes; we don't have an easy way to mute that one right now, so we should either explain it, or remove observations that have some isotypes missing (prior to calling `est.incidence.by()`.)
> 
> @d-morrison I thought I would try to inspect the count of antigen isotypes by adding the n for each strata to the `summary()` in line 113 (i.e. to `ab_summary` on lines 48-63 in `summary.pop_data.R`), but was having issues, so I scratched that and just added more explanation in lines 238-244 for now. Feel free to tinker with it if you'd like, otherwise I think it can be updated later.

Fine to postpone this for now; I'll create an Issue so we don't forget to loop back to this.

2024-09-30 06:45 UTC, d-morrison approved these changes
Thanks - looks great!

2024-09-30 06:45 UTC, merged