Adding examples
UCD-SERG/serocalculator pull request #79
Opened 2024-02-16 01:13 UTC by kristinawlai

All checks pass! This was fun in a tedious puzzle sort of way

2024-02-16 19:29 UTC, d-morrison requested changes
Looking good overall! A couple of remaining to-dos:

- [ ] Looks like something is wrong with `enteric_fever_example.Rmd`:

https://github.com/UCD-SERG/serocalculator/actions/runs/7924593344/job/21636409702?pr=79#step:6:121

I left a comment in `autoplot.pop_data()` where I think the issue is coming from.


- [x] Also, please revise the example for `llik()` as discussed in the comment.

2024-02-16 19:29 UTC, d-morrison commented on R/autoplot.pop_data.R
> +    ggplot2::ggplot(aes(x = .data$result)) +
@kristinawlai , why the change from `value` to `result`?

2024-02-16 19:29 UTC, d-morrison commented on R/llik.R
> +#' #generate cross-sectional data
@kristinawlai Please rework this example to use data from OSF instead of simulated data. I think it will be more concise and understandable that way.

2024-02-20 20:53 UTC, kristinawlai commented on R/autoplot.pop_data.R
> +    ggplot2::ggplot(aes(x = .data$result)) +
@d-morrison that was an attempt to match some of the code, but I just switched it back after rerunning with `clean_pop_data()`. So should be fixed. But I'm getting the error below also within `autoplot.pop_data`. Here's the error that shows up in `enteric_fever_example.Rmd`:

<img width="511" alt="image" src="https://github.com/UCD-SERG/serocalculator/assets/57973437/dd132d14-4c78-4d3e-96db-367bda67b47c">

 and then where I think it's occuring in `autoplot.pop_data`, but not sure what the error is:
<img width="561" alt="image" src="https://github.com/UCD-SERG/serocalculator/assets/57973437/5cc9e492-c42a-4a3c-ba79-c0d267b80976">

2024-02-20 21:41 UTC, d-morrison commented
@kristinawlai Something appears to be wrong with one of the new documentation examples; try using `devtools::run_examples()` to track down which one. [You're in good company with this error.](https://devtools.r-lib.org/reference/run_examples.html#:~:text=One%20of%20the%20most%20frustrating%20parts%20of%20R%20CMD%20check%20is%20getting%20all%20of%20your%20examples%20to%20pass%20%2D%20whenever%20one%20fails%20you%20need%20to%20fix%20the%20problem%20and%20then%20restart%20the%20whole%20process.%20This%20function%20makes%20it%20a%20little%20easier%20by%20making%20it%20possible%20to%20run%20all%20examples%20from%20an%20R%20function.)

2024-02-21 23:56 UTC, kristinawlai commented
@d-morrison all checks pass now! Check it out and merge?

2024-02-22 03:07 UTC, d-morrison approved these changes
Everything looks good! Great work.

2024-02-22 03:07 UTC, merged