Typhoid vignette
UCD-SERG/serocalculator pull request #9
Opened 2023-09-05 20:43 UTC by kristinawlai

Updated typhoid vignette data loading and started updating explanatory text.

2023-09-06 19:11 UTC, d-morrison commented on vignettes/typhoid-seroincidence.Rmd
> +p.hlye.IgG  <- read_csv("simpophlyeigg.2.csv") %>%
I think the checks are currently failing due to this line; fix a la https://r-pkgs.org/data.html#sec-data-system-file ?

2023-09-06 19:17 UTC, d-morrison requested changes
Getting close to ready for merge! I left some in-line comments for details to iron out.

2023-09-06 19:17 UTC, d-morrison commented on vignettes/installation.Rmd
> +# Install Windows binary package \"serocalculator\" directly from internet ECDC website:
this option should be removed

2023-09-06 19:17 UTC, d-morrison commented on README.html
I don't think we want to track the html version of this file in git; delete before next commit?

2023-09-06 19:17 UTC, d-morrison commented on README.md
> +Windows users will need to install Rtools, which contains a collection of tools for building and employing R packages that are still in development.
Did the version of Rtools installed by devtools not work? I can't remember what happened with that.

2023-10-06 19:02 UTC, d-morrison commented
@kristinawlai I pushed some commits to the `typhoid_vignette` branch on your fork to try to fix the check errors we were getting, but there are some file conflicts that I can't resolve (since we're still operating on your fork for now). Would you please take a look and try to sort them out? There should be a "Resolve conflicts" button somewhere on the this page, which will take you to an online file editor. The html file just needs to be deleted, so that will hopefully be simple to resolve, but in the `typhoid-seroincidence.Rmd` file, there might be some strange-looking markings showing the line-by-line conflicts. Take a look at those and see if you can edit the file to how you think it should be? If you get stuck, please let me know!

2023-10-10 17:17 UTC, kristinawlai commented
@d-morrison The changes are too complex to resolve in the web editor, so I can't see what to edit. Can you show me how to do this via command line or other best way to do this? We can discuss on our call.

2023-11-07 21:21 UTC, closed without merging